- name: configure ansible instance
  hosts: ansible
  roles:
    - common

- name: configure web instance
  hosts: web
  roles:
    - common
    - web

- name: configure db instance
  hosts: db
  roles:
    - common
    - db
