- name: configure ansible instance
  hosts: ansible
  become: true
  become_user: root
  roles:
    - common

- name: configure web instance
  hosts: web
  become: true
  become_user: root
  roles:
    - web
    - common

- name: configure db instance
  hosts: db
  become: true
  become_user: root
  roles:
    - db
    - common
