- name: configure ansible instance
  hosts: ansible
  become: true
  become_user: root

- name: configure web instance
  hosts: web
  become: true
  become_user: root
  roles:
    - web

- name: configure db instance
  hosts: db
  become: true
  become_user: root
  roles:
    - db
